spring:
  velocity:
    secret: Create a long random string
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: 127.0.0.1:57553
  datasource:
    url: jdbc:postgresql://localhost:5432/ogcloud
    username: postgres
    password: postgres
  kube:
    master-url: https://127.0.0.1:<port>
    certificate-authority-data: |
      -----BEGIN CERTIFICATE-----
      Content of your certificate here! If using Minikube then C:\Users\<your user>\.minikube
      -----END CERTIFICATE-----
    client-certificate-data: |
      -----BEGIN CERTIFICATE-----
      Content of your certificate here! If using Minikube then C:\Users\<your user>\.minikube
      -----END CERTIFICATE-----
    client-key-data: |
      -----BEGIN RSA PRIVATE KEY-----
      Content of your certificate here! If using Minikube then C:\Users\<your user>\.minikube
      -----END RSA PRIVATE KEY-----
